openconnect:
  image: cheneyyan/openconnect
  command:  bash /openconnect/start.sh
  net: host
  stop_signal: SIGINT
  privileged: yes
  restart: on-failure:5
  volumes:
    - ./credential.yaml:/credential.yaml
